name: Ubuntu VPS
on: workflow_dispatch  # Jalankan secara manual
jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Update dan Install Paket
        run: |
          sudo apt update && sudo apt install -y htop curl wget
          echo "Ubuntu VPS siap digunakan!"
