name: Build Kernel

on:
  push:
    branches:
      - main  # Jalankan ketika ada push ke branch main
  workflow_dispatch:  # Bisa dijalankan secara manual di GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 --branch 10 https://github.com/NusantaraROM-Devices/kernel_xiaomi_rolex.git kernel

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-9 g++-9 \
                             gcc-aarch64-linux-gnu \
                             make bc flex bison \
                             cpio libssl-dev libelf-dev \
                             python3-distutils python3-dev

      - name: Apply Patch to dtc-parser.y
        run: |
          sed -i '/#define YYLTYPE_IS_DECLARED 1/i #ifndef YYLTYPE_IS_DECLARED' kernel/scripts/dtc/dtc-parser.y
          sed -i '/#define YYLTYPE_IS_DECLARED 1/a #endif' kernel/scripts/dtc/dtc-parser.y

      - name: Set up GCC 9 as default
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100

      - name: Configure Kernel
        run: |
          cd kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig

      - name: Build Kernel
        run: |
          cd kernel
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-kernel
          path: |
            kernel/arch/arm64/boot/Image.gz-dtb
            kernel/out/*.img  # Jika ada file output lain
